### ISSUE TITLE
Domain Entity 

### ISSUE THREAD

**Issue by now-water** [KNU-CSE-APP/Server#11]
## 설계한 비즈니스 엔티티

- [x] User
- [x] Reservation
- [x] ClassSeat
- [x] ClassRoom
- [x] Board
- [x] Comment
- [x] Reply
- ~~WriteBoard~~
- ~~WriteComment~~

![image](https://user-images.githubusercontent.com/51476083/125241967-1cb84480-e327-11eb-8952-2b005136f9f1.png)

**Comment by now-water** [comment]
도메인 엔티티 구현 완료

**Comment by kcm0147** [comment]
1. writeBoard, writeComment 제거
2. Reply Entity 제거 후 Comment에 합치기
